
// Home page
export const HOME_UPDATE_ANIMATION = 'HOME_UPDATE_ANIMATION';

// Modals
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL_WITH_SETTINGS = 'OPEN_MODAL_WITH_SETTINGS';

// Filtering component
export const OPEN_FILTER_SELECTION = 'OPEN_FILTER_SELECTION';
export const CLOSE_FILTER_SELECTION = 'CLOSE_FILTER_SELECTION';
export const UPDATED_LABEL_FILTER_SELECTION = 'UPDATED_LABEL_FILTER_SELECTION';
export const UPDATED_CATEGORY_FILTER_SELECTION = 'UPDATED_CATEGORY_FILTER_SELECTION';
export const UPDATED_CATEGORY_FILTER_SELECTION_UNSELECT = 'UPDATED_CATEGORY_FILTER_SELECTION_UNSELECT';
export const RESET_FILTER = 'RESET_FILTER';
export const RESET_SELECTED = 'RESET_SELECTED';

// Header component
export const APP_HEADER_SHOW = 'APP_HEADER_SHOW';
export const APP_HEADER_HIDE = 'APP_HEADER_HIDE';

// Other
export const GET_SAMPLE = 'GET_SAMPLE';
export const SAMPLE_ERROR = 'SAMPLE_ERROR';
