name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: echo '${{ secrets.ENVIRONMENT_FILE }}' > .env
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_K3LLYDEV_PORTFOLIO }}'
          channelId: live
          projectId: k3llydev-portfolio
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
