name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: echo '${{ secrets.ENVIRONMENT_FILE }}' > .env
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Enable Firebase web frameworks
        run: firebase experiments:enable webframeworks
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --message "Deployed automatically from GitHub Actions."
